name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
            go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum

      - name: Run unit tests
        run: make unit-test
